
[[colors.indexed_colors]]
color = "#ff9e64"
index = 16

[[colors.indexed_colors]]
color = "#db4b4b"
index = 17

[colors.bright]
black = "#414868"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
magenta = "#bb9af7"
red = "#f7768e"
white = "#c0caf5"
yellow = "#e0af68"

[colors.normal]
black = "#15161e"
blue = "#2b84f2"
cyan = "#44dafa"
green = "#9af26a"
magenta = "#a97ff4"
red = "#fa3c71"
white = "#a9b1d6"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[cursor]
unfocused_hollow = true

[font]
size = 12.75

[font.normal]
family = "Hack Nerd Font"

[[keyboard.bindings]]
chars = "\u001BF"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[selection]
save_to_clipboard = true

[window]
blur = true
opacity = 0.85

[window.padding]
x = 5
y = 5

[general]
live_config_reload = true
