#!/bin/bash
#
# Create backup tar file of this directory
. _utils


#######################################
# Create backup tar file of this directory
# Arguments:
#   None
# Outputs:
#   backup_file
#######################################

BACKUPFILE=backup-$(date +%m-%d-%Y)
archive=${1:-$BACKUPFILE}

find . -mtime -1 -type f -print0 | xargs -0 tar rvf "$archive.tar"
echo "Directory $PWD backed up in archive file \"$archive.tar.gz\"."
exit 0