#!/bin/bash
#
. _utils


#######################################
# Super advanced search with menu
# Arguments:
#   None
# Outputs:
#   None
# press f
# see all the options
# press the option I want
#######################################


option_picked(){
    msgcolor=`echo "\033[01;31m"` # bold red
    normal=`echo "\033[00;00m"` # normal white
    message=${@:-"${normal}Error: No message passed"}
    printf "${msgcolor}${message}${normal}\n"
}

show_menu(){
    normal=`echo "\033[m"`
    menu=`echo "\033[36m"` #Blue
    number=`echo "\033[33m"` #yellow
    bgred=`echo "\033[41m"`
    fgred=`echo "\033[31m"`
    printf "\n${menu}*********************************************${normal}\n"
    printf "${menu}**${number} 1)${menu} Search every line, in every file, and open that file${normal}\n"
    printf "${menu}**${number} 2)${menu} Search every line, in every file, and return the file location${normal}\n"
    printf "${menu}**${number} 3)${menu} Find exact file name and vi${normal}\n"
    printf "${menu}**${number} 4)${menu} Find exact search file name from root and vi${normal}\n"
    printf "${menu}**${number} 5)${menu} Find directory and cd into it${normal}\n"
    printf "${menu}**${number} 6)${menu} Search and replace text in files${normal}\n"
    printf "${menu}**${number} 7)${menu} Show recent files and directories${normal}\n"
    printf "${menu}**${number} 8)${menu} Search hidden files and directories and cd into it${normal}\n"
    printf "${menu}**${number} 9)${menu} Search hidden files and directories and return the location${normal}\n"
    printf "${menu}*********************************************${normal}\n"
    printf "Please enter a menu option and enter or ${fgred}x to exit. ${normal}"
}

main(){
    show_menu
    while read -p 'Enter value: ' opt; do
        if [ "$opt" == "x" ]; then
            exit
        elif [ "$opt" == "" ]; then
            option_picked "Pick an option from the menu"
            show_menu
        elif [ "$opt" -ge 1 -a "$opt" -le 9 ]; then
            case $opt in
                1)
                    option_picked "Search every line, in every file, and open that file"
                    file=$(rg . | fzf | cut -d ":" -f 1)
                    if [ -f "$file" ]; then
                        vi "$file"
                    else
                        option_picked "File not found."
                    fi
                    ;;
                2)
                    option_picked "Search every line, in every file, and return the file location"
                    file=$(rg . | fzf | cut -d ":" -f 1)
                    if [ -f "$file" ]; then
                        echo "$file"
                    else
                        option_picked "File not found."
                    fi
                    ;;
                3)
                    option_picked "Find exact file name and vi"
                    file=$(find . -type f | fzf)
                    if [ -f "$file" ]; then
                        vi "$file"
                    else
                        option_picked "File not found."
                    fi
                    ;;
                4)
                    option_picked "Find exact search file name from root and vi"
                    echo twf --previewCmd="bat --color=always --style=grid,numbers {}" -preview=true
                    ;;
                5)
                    option_picked "Find directory and cd into it"
                    dir=$(find * -type d | fzf --exact)
                    if [ -d "$dir" ]; then
                        cd "$dir"
                    else
                        option_picked "Directory not found."
                    fi
                    ;;
                6)
                    option_picked "Search and replace text in files"
                    read -p "Enter text to search: " search_text
                    read -p "Enter replacement text: " replace_text
                    rg -l "$search_text" | xargs sed -i "s/$search_text/$replace_text/g"
                    ;;
                7)
                    option_picked "Show recent files and directories"
                    ls -lt | awk '{print $9}' | fzf
                    ;;
                8)
                    option_picked "Search hidden files and directories and cd into it"
                    dir=$(find . -type d -name '.*' | fzf --exact)
                    if [ -d "$dir" ]; then
                        cd "$dir"
                    else
                        option_picked "Directory not found."
                    fi
                    ;;
                9)
                    option_picked "Search hidden files and directories and return the location"
                    file=$(find . -type d -name '.*' | fzf --exact)
                    if [ -d "$file" ]; then
                        echo "$file"
                    else
                        option_picked "Directory not found."
                    fi
                    ;;
                *)
                    option_picked "Invalid option. Please choose a number from 1 to 9 or 'x' to exit."
                    ;;
            esac
        else
            option_picked "Invalid option. Please choose a number from 1 to 9 or 'x' to exit."
        fi
    done
}

main
