#!/bin/bash
#
# Fuzzy find and open files
. _utils

#######################################
# Fuzzy find and open files
# Arguments:
#   None
# Outputs:
#   Opens selected file with default app
#######################################

main() {
    local file=$(fzf --preview 'bat --style=numbers --color=always --line-range :500 {}')
    
    if [ -n "$file" ]; then
        echo -e "${GREEN}Opening: $file${NC}"
        open "$file"
    fi
}

main "$@" 