#!/bin/bash
#
# Create new git branch
. _utils


#######################################
# Create new git branch
# Arguments:
#   None
# Outputs:
#   None
#######################################

current="$(git branch | grep "*" | cut -b 3-)"

# if arg is not set
if [ -z "${1}" ]; then
    echo -e "Name of new branch?"
    read branch
    # and if on master
    if [ "$current" == 'master' ];then
        echo -e "Creating ${YELLOW} $branch ${NC} from ${RED}Master${NC}..."
        git checkout master && git pull origin master && git checkout -b "$branch"
    else
        #if not on master
        echo -e "Create ${BBLUE} $branch ${NC} from ${YELLOW} $current (c) ${NC} or from ${RED}Master (m)${NC}?"
        read -p "current(c) / Master(m) ?" cm
        [ $cm == 'c' ] && git checkout -b "$branch"
        [ $cm == 'm' ] && git checkout master && git pull origin master && git checkout -b "$branch"
    fi
#otherwise use $1 arg as branch name
else
    if [ "$current" == 'master' ];then
        echo -e "Creating ${BBLUE} $1 ${NC} from ${RED}Master${NC}?"
        git checkout master && git pull origin master && git checkout -b "$1"
    else
        echo -e "Create ${BBLUE} $1 ${NC} from ${YELLOW} $current (c) ${NC} or from ${RED}Master (m)${NC}?"
        read -p "current(c) / Master(m) ?" cm
        [ $cm == 'c' ] && git checkout -b "$1"
        [ $cm == 'm' ] && git checkout master && git pull origin master && git checkout -b "$1"
    fi
fi
