#!/bin/bash
#
# Update all nested directories in current directory to main
. _utils


#######################################
# Update all nested directories in current directory to main
# Arguments:
#   None
# Outputs:
#   None
#######################################
function run() {
    for repo in basename "$PWD"
    do
        if [[ ! -d $repo/.git ]]
        then
            continue
        fi

        cd $repo
        repoName=$(basename $repo)
        branch=$(git symbolic-ref --short HEAD)

        if [[ $branch == "main" ]]
        then
            echo -n "Updating $repoName... "
            git pull origin main > /dev/null 2>&1
            RESULT=$?

        if [ $RESULT -eq 0 ]
        then
            echo -e "${GREEN}DONE${NC}"
        else
            echo -e "${RED}FAILED!!!${NC}"
        fi
        else
        echo -e "${YELLOW}Skipping $repoName on branch $branch${NC}"
        fi

    done
}

run